name: Run Codeception test cases

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run:  composer update

    - name: Run chromedriver
      run:  nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &

    - name: Run test cases
      run:  php vendor/bin/codecept run acceptance --steps
